import type { VercelRequest, VercelResponse } from '@vercel/node';
import { createClient } from '@supabase/supabase-js';
import { GoogleGenAI } from '@google/genai';

const DEFAULT_CHUNKS = [
  { id: "chunk-1", page_number: 11, chapter: "Lesson 1: The Rich Don't Work for Money", text: "The poor and the middle class work for money. The rich have money work for them. Robert Kiyosaki's rich dad explained that most people are driven by two emotions: fear and greed. First, the fear of being without money motivates them to work hard, and then once they get a paycheck, greed or desire starts them thinking about all the wonderful things money can buy. This sets up the pattern of the Rat Race: get up, go to work, pay bills, get up, go to work, pay bills. Their lives are run by fear and desire, and they refuse to use their brains to think for themselves." },
  { id: "chunk-2", page_number: 18, chapter: "Lesson 1: The Rich Don't Work for Money", text: "Rich dad taught Robert and Mike that money is an illusion, just like the carrot in front of the donkey. It is only because of fear and greed that the illusion of money is held together by millions of people who believe that money is real. Money is actually made up. The rich don't work for money because they understand how to create assets that generate money even when they are asleep. If you work for money, you give the power to your employer. If money works for you, you keep the power and control it." },
  { id: "chunk-3", page_number: 35, chapter: "Lesson 2: Why Teach Financial Literacy?", text: "Rule Number One: You must know the difference between an asset and a liability, and buy assets. If you want to be rich, this is all you need to know. It is Rule No. 1. It is the only rule. Rich people acquire assets. Poor and middle class acquire liabilities that they think are assets. An asset is something that puts money in my pocket, whether I work or not. A liability is something that takes money out of my pocket. The lack of financial literacy is the core reason for financial struggle." },
  { id: "chunk-4", page_number: 42, chapter: "Lesson 2: Why Teach Financial Literacy?", text: "A house is a liability, not an asset, for most people. Robert Kiyosaki explains that a house takes money out of your pocket through mortgage payments, property taxes, insurance, maintenance, and utilities. If you buy a house that is too expensive, you lose the opportunity to invest that cash flow in income-generating assets. Although a house can appreciate, it does not put cash in your pocket monthly; instead, it requires constant cash outflows. Therefore, Kiyosaki considers a primary residence to be a liability, while an investment property that generates net rental income is an asset." },
  { id: "chunk-5", page_number: 48, chapter: "Lesson 2: Why Teach Financial Literacy?", text: "The financial difference between the rich, the poor, and the middle class is illustrated by cash flow patterns. The cash flow of a poor person consists only of an income (job) which is immediately spent on expenses (food, rent, clothes, taxes). They have no assets or liabilities. The cash flow of a middle-class person consists of income (job) which goes to pay for liabilities (mortgages, car loans, credit cards) and expenses. The cash flow of a rich person is generated by their asset column (stocks, bonds, real estate, intellectual property), which provides passive income that exceeds their expenses, allowing them to reinvest in more assets." },
  { id: "chunk-6", page_number: 71, chapter: "Lesson 3: Mind Your Own Business", text: "To become financially secure, a person needs to mind their own business. Your business revolves around your asset column, as opposed to your profession, which revolves around your income column. Financial struggle is often the result of people working all their lives for someone else. Many people will have nothing at the end of their working days. Minding your own business means keeping your asset column strong. Once a dollar goes into it, never let it come out. Think of it as your employee working 24 hours a day to build wealth." },
  { id: "chunk-7", page_number: 74, chapter: "Lesson 3: Mind Your Own Business", text: "What kind of assets should you acquire? Robert Kiyosaki suggests several categories of real assets: 1. Businesses that do not require my presence (I own them, but they are managed or run by other people). 2. Stocks. 3. Bonds. 4. Income-generating real estate. 5. Notes (promissory notes/IOMs). 6. Royalties from intellectual property such as music, scripts, patents. 7. Anything else that has value, produces income or appreciates, and has a ready market." },
  { id: "chunk-8", page_number: 83, chapter: "Lesson 4: The History of Taxes and the Power of Corporations", text: "The rich are not taxed as heavily as the middle class because they understand the legal power of corporations. A corporation is not a physical thing; it is merely a file folder with some legal documents in it, sitting in an attorney's office. A corporation offers massive tax advantages. While an employee earns, gets taxed, and then tries to live on what is left, a corporation earns, spends everything it can (including business expenses, travel, cars), and is only taxed on what is left. This is one of the biggest legal tax loopholes used by the wealthy." },
  { id: "chunk-9", page_number: 89, chapter: "Lesson 4: The History of Taxes and the Power of Corporations", text: "Financial IQ is made up of knowledge from four broad areas: 1. Accounting: Financial literacy, or the ability to read and understand financial statements. 2. Investing: The science of money making money, involving strategies and formulas. 3. Understanding markets: The science of supply and demand, matching an investment with market conditions. 4. The Law: Understanding tax advantages and protection from lawsuits. Specifically, using corporations to shield assets and reduce tax liabilities legally." },
  { id: "chunk-10", page_number: 99, chapter: "Lesson 5: The Rich Invent Money", text: "Often in the real world, it's not the smart who get ahead, but the bold. Financial genius requires both technical knowledge and courage. Most people are so afraid of losing that they lose. They play the game of life too safely. Robert Kiyosaki explains that financial intelligence is simply having more options. If the opportunities aren't coming your way, what else can you do to improve your financial position? If an opportunity falls in your lap and you have no money, and the bank won't talk to you, what else can you do to get that opportunity to work for you? The rich invent money by finding creative solutions to financial problems." },
  { id: "chunk-11", page_number: 106, chapter: "Lesson 5: The Rich Invent Money", text: "There are two types of investors: 1. The most common type is those who buy a packaged investment from a retail outlet (real estate company, stockbroker, or financial planner). 2. The second type is investors who create investments. This investor assembles the deal, finds smart people, and coordinates them. To be the second type, you must develop three key skills: 1. How to find an opportunity that everyone else missed. 2. How to raise money (without going to standard banks). 3. How to organize smart people (hiring people who are smarter than you)." },
  { id: "chunk-12", page_number: 127, chapter: "Lesson 6: Work to Learn - Do not Work for Money", text: "Robert Kiyosaki recommends that young people seek work for what they will learn, more than what they will earn. Look ahead at what skills you want to acquire before choosing a specific profession. Kiyosaki's educated dad (poor dad) believed in specialization and job security (getting a PhD, becoming a specialist). In contrast, rich dad recommended that Robert learn a little about a lot. He worked in different departments at his rich dad's companies to understand sales, shipping, marketing, and accounting. The most important specialized skill is sales and marketing: the ability to sell is the single most important skill for personal wealth." },
  { id: "chunk-13", page_number: 133, chapter: "Lesson 6: Work to Learn - Do not Work for Money", text: "The primary management skills necessary for financial success are: 1. Management of cash flow. 2. Management of systems (including yourself, your family, and your business). 3. Management of people. Furthermore, the most important communication skills are selling and understanding marketing. The ability to sell to communicate to another human being, be it a customer, employee, boss, spouse, or child is the base skill of personal success." },
  { id: "chunk-14", page_number: 147, chapter: "Overcoming Obstacles", text: "Once people have become financially literate, they may still face obstacles to financial independence. The five primary obstacles are: 1. Fear of losing money. 2. Cynicism or doubt. 3. Laziness (often disguised as staying busy). 4. Bad habits. 5. Arrogance. For fear, rich dad said: If you hate risk and worry, start early. Everyone wants to be rich, but most people are terrified of losing money. The rich handle failure differently; they use failure to inspire them to win." },
  { id: "chunk-15", page_number: 153, chapter: "Overcoming Obstacles - Cynicism", text: "Doubt and cynicism keep most people poor. Cynics complain, while winners analyze. A cynic will say, What if the market crashes? or What if there is a tenant who will not pay? These doubts paralyze them. Rich dad taught that Chicken Littles run around shouting The sky is falling and their noise is heard by everyone. Winners analyze the real risks and find opportunities. For example, during real estate down cycles, cynics are too scared to buy, while winners realize it is a clearance sale and acquire properties at a discount." },
  { id: "chunk-16", page_number: 158, chapter: "Overcoming Obstacles - Laziness", text: "Busy people are often the most lazy. They stay busy at work, with friends, or watching TV to avoid confronting their underlying financial problems. This is a form of emotional laziness. How do you cure laziness? The cure is a little greed. Ask yourself, What is in it for me? and How can I afford it? instead of saying I cannot afford it. The words I cannot afford it shut down your brain. The question How can I afford it? opens up your mind, forcing it to think and create solutions." },
  { id: "chunk-17", page_number: 161, chapter: "Overcoming Obstacles - Bad Habits and Arrogance", text: "Our lives are shaped more by our habits than by our education. A key habit of the rich is paying themselves first. Most people get their paycheck and pay their bills first (landlord, tax collector, credit cards), leaving nothing for savings or investments. The rich pay themselves first reinvesting in their assets and use the pressure of unpaid creditors to motivate them to find creative ways to generate more income. Arrogance is also an obstacle; it is ego plus ignorance. When you are arrogant, you believe what you do not know is unimportant." },
  { id: "chunk-18", page_number: 167, chapter: "10 Steps to Awaken Your Financial Genius", text: "Step 1: Find a Reason Greater than Reality (The Power of Spirit). If you do not have a strong reason, the road ahead is too tough. Step 2: Make Daily Choices (The Power of Choice). We choose our habits and what we put in our heads. Invest in your education first. Step 3: Choose Friends Carefully (The Power of Association). Learn from both wealthy friends (how they make money) and struggling friends (what not to do). Step 4: Master a Formula, then Learn a New One (The Power of Rapid Learning). Be careful what you study because you become what you put in your mind." },
  { id: "chunk-19", page_number: 174, chapter: "10 Steps to Awaken Your Financial Genius - Continued", text: "Step 5: Pay Yourself First (The Power of Self-Discipline). If you cannot control yourself, do not try to get rich. Keep your expenses low and build assets. Step 6: Pay Your Brokers Well (The Power of Good Advice). Professional brokers provide valuable information and save you time. Their commissions are small compared to the money they make you. Step 7: Be an Indian Giver (The Power of Getting Something for Nothing). Look for investments with a quick return of capital, while keeping a piece of the asset for free (e.g., getting your seed capital back in a year and keeping stock options)." },
  { id: "chunk-20", page_number: 181, chapter: "10 Steps to Awaken Your Financial Genius - Continued", text: "Step 8: Use Assets to Buy Luxuries (The Power of Focus). Do not buy luxuries on credit. If you want a nice car, first invest in assets (like real estate or stocks) until they generate enough cash flow to pay for the car. This builds financial discipline. Step 9: Choose Heroes (The Power of Myth). Emulate heroes like Warren Buffett or Donald Trump to make investing seem easy. Step 10: Teach and You Shall Receive (The Power of Giving). If you want money, love, or sales, first give them away. Generosity returns tenfold." }
];

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
    const geminiKey = process.env.GEMINI_API_KEY;
    if (!url || !key) {
      return res.status(500).json({ error: 'Missing Supabase credentials' });
    }
    if (!geminiKey) {
      return res.status(500).json({ error: 'Missing GEMINI_API_KEY' });
    }

    const supabase = createClient(url, key);

    const { count } = await supabase
      .from('chunks')
      .select('*', { count: 'exact', head: true })
      .eq('source', 'Rich Dad Poor Dad');

    if (count && count > 0) {
      return res.json({
        success: true,
        message: 'Vector store already initialized.',
        chunksCount: count,
        bookName: 'Rich Dad Poor Dad (Default Edition)',
        totalPages: 188,
      });
    }

    await supabase.from('chunks').delete().neq('id', '__nonexistent__');

    const ai = new GoogleGenAI({ apiKey: geminiKey });
    const texts = DEFAULT_CHUNKS.map(
      (c) => `${c.chapter} (Page ${c.page_number}): ${c.text}`
    );

    const embResponse = await ai.models.embedContent({
      model: 'text-embedding-004',
      contents: texts,
    });

    const embeddings: number[][] = [];
    if (embResponse.embeddings) {
      for (const emb of embResponse.embeddings) {
        if (emb.values) embeddings.push(emb.values);
      }
    }

    const rows = DEFAULT_CHUNKS.map((chunk, i) => ({
      id: chunk.id,
      text: chunk.text,
      page_number: chunk.page_number,
      source: 'Rich Dad Poor Dad',
      chapter: chunk.chapter || null,
      embedding: JSON.stringify(embeddings[i] || new Array(768).fill(0)),
    }));

    const { error } = await supabase.from('chunks').insert(rows);
    if (error) throw error;

    return res.json({
      success: true,
      message: 'Default chunks loaded.',
      chunksCount: rows.length,
      bookName: 'Rich Dad Poor Dad (Default Edition)',
      totalPages: 188,
    });
  } catch (err: any) {
    return res.status(500).json({ error: err.message || 'Failed to reset.' });
  }
}
